### ISSUE TITLE
When uploading multiple .gpx,  SpringSecurityContext is null

### ISSUE THREAD

**Issue by loreV** [loreV/SeC#157]

**Comment by loreV** [comment]
```
java.lang.NullPointerException: null
	at org.sc.configuration.auth.KeycloakAuthAttributeHelper.getUsername(KeycloakAuthAttributeHelper.java:34) ~[classes/:na]
	at org.sc.manager.TrailFileManager.getTrailRawModel(TrailFileManager.kt:106) ~[classes/:na]
	at org.sc.controller.admin.AdminTrailImporterController.lambda$processUploadedFiles$5(AdminTrailImporterController.java:107) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[na:na]
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

**Comment by loreV** [comment]
Issue resolved by taking a different - non-spring bean approached. The auth data is propagated to the whole context from the controller on
